package.json
src/_internals/commands/implementations/Advancement.ts
src/_internals/commands/implementations/Attribute.ts
src/_internals/commands/implementations/Clone.ts
src/_internals/commands/implementations/Data.ts
src/_internals/commands/implementations/Datapack.ts
src/_internals/commands/implementations/Debug.ts
src/_internals/commands/implementations/DefaultGamemode.ts
src/_internals/commands/implementations/Difficulty.ts
src/_internals/config.ts
src/_internals/datapack/Datapack.ts
src/_internals/index.ts
src/core.ts

CHANGELOG:
- More commands now have comments
- You can now create a "sandstone.json" file, that must be **in the same folder** than the file you're running. It can contain a "namespace" key, that gives the default namespace for Sandstone to use.
Example:
```json
{
"namespace": "mynamespace"
}
```

Added a sandstone.json configuration file, & more commands comments

---

package.json
src/_internals/arguments/resources/predicate.ts
src/_internals/datapack/Datapack.ts
src/_internals/datapack/resourcesTree.ts
src/_internals/generalTypes.ts
src/_internals/resources/McFunction.ts
src/_internals/resources/Predicate.ts
src/_internals/resources/Tag.ts
src/_internals/variables/Selector.ts
tests/test.ts

Changelog:
- Selectors `predicate` field now directly accepts a predicate
- Selectors `scores` field now accepts +Infinity and -Infinity when specifying boundaries. Example: `scores: {deaths: [1, +Infinity]}`
- Fixed `getName` being not accessible on mcfunctions
- Function tags now directly accept mcfunctions

Sandstone 0.4.4 - A few improvements

---

package.json
scripts/setupPackage.js
src/_internals/flow/Flow.ts
src/arguments.ts
src/commands.ts
src/core.ts
src/index.ts
src/variables.ts
tests/menu.ts
tests/test.ts
tsconfig.json
yarn.lock

Changelog: 
- Path aliases were previously resolved at runtime, using `module-alias`. However, it didn't resolve in declaration (.d.ts) files, leading to incorrect type inferring. To solve this problem, Sandstone now uses a new Typescript compiler, `ttypescript`. It allows the use of compiler plugins: Sandstone uses the `typescript-transform-paths` plugin, which resolves all path aliases at build time.
- While/for loops weren't including the `run` keyword inside the recursive function. It is now solved.

v0.4.5: Path aliases now resolved at build time - Fixed while/for loops not working properly

---

src/_internals/commands/decorators.ts
src/_internals/datapack/BasePath.ts
src/_internals/datapack/Datapack.ts
src/_internals/datapack/saveDatapack.ts
src/_internals/flow/Flow.ts
src/_internals/flow/conditions.ts
src/_internals/resources/MCFunctionClass.ts
src/_internals/resources/Predicate.ts
src/_internals/variables/PlayerScore.ts
src/_internals/variables/Selector.ts
src/core.ts
tests/test.ts

This pull request adds the ability to await a `sleep` function, which internally uses `/schedule` to allow MCFunctions to run delayed commands.
The syntax is `await sleep(10) / await sleep('1s')`.
Since this effect needs to work flawlessly in every Sandstone abstraction, this PR also adds:
- Asynchronous while & doWhile statements
- Asynchronous if/else if/else statements

Added delaying statements

---

src/_internals/arguments/basics.ts
src/_internals/commands/implementations/Schedule.ts
src/_internals/commands/implementations/Time.ts
src/_internals/datapack/Datapack.ts
src/_internals/datapack/minecraft.ts
src/_internals/datapack/saveDatapack.ts
src/_internals/flow/Flow.ts
src/_internals/resources/MCFunctionClass.ts
src/_internals/variables/PlayerScore.ts
src/types.ts

Changelog:
- Added `if/else` inlining & optimization ([SAND-4]). Now:
+ Single `_.if` won't create the whole boilerplate anymore.
+ 1-line `_.if` and `_.elseIf` will be inlined
- Added the `runEach` option for `MCFunction`, allowing a function to run in loop with a given delay between each call. [SAND-5]
- Added an `indentation` option for `savePack`, modifying the indentation used for all JSON & MCMeta files. [SAND-2]
[SAND-4]: https://themrzz.atlassian.net/browse/SAND-4
[SAND-5]: https://themrzz.atlassian.net/browse/SAND-5
[SAND-2]: https://themrzz.atlassian.net/browse/SAND-2

Added if/else inlining, and some options

---

package.json
src/_internals/arguments/basics.ts
src/_internals/variables/Selector.ts

Fixed two breaking bugs:
- `Selector` wasn't taking `'@e'` as an argument
- Scoreboard players operation were taking `<=` and `>=` as operation, instead of `<` and `>`

Fixed two breaking bugs

---

package.json
src/_internals/commands/implementations/Advancement.ts
src/_internals/resources/MCFunctionClass.ts
src/_internals/resources/Tag.ts

Changelog:
- `Tag` values now default to `[]`
- `MCFunction` `tags` arguments now accepts Sandstone function tags
- `/advancement` now accepts Sandstone advancements
- On `MCFunction`, changed `runEach` behavior when `runOnLoad` is false. Now, the function won't be ran at all, and the user will have to manually run it.

0.9.0 - Several improvements

---

package.json
src/_internals/arguments/resources/advancement.ts
src/_internals/datapack/BasePath.ts
src/_internals/datapack/Datapack.ts
src/_internals/datapack/saveDatapack.ts
src/_internals/variables/PlayerScore.ts
src/types.ts

Changelog:
- Fixed playerScore.dividedBy using `*=` and not `/=`
- Set default Tag value to `[]`
- Set default AdvancementType generic criteria names to `string`
- Added BasePathClass & BasePathOptions to exports
- Added 2 arguments for scripts: `destination` & `dataPackName`

Several fixes - v0.9.1

---

src/_internals/variables/Selector.ts

Changelog:
- Fixed swap operator being `<>` instead of `><` ;
- Fixed a circular dependency error, leading to `setblock` crashing ;
- Fixed Selectors lacking the `nbt` property.

Fixed 3 errors

---

package.json
src/_internals/commands/implementations/Team.ts
src/_internals/flow/Flow.ts
src/_internals/variables/PlayerScore.ts
tsconfig.json

Changelog:
- Minimum required NodeJS version is now 12.9.0 (previously: 14.0.0).
- All PlayerScore methods now accepts a `PlayerScore | number` argument.
- Fixed `/team modify` command lacking the team parameter.

Fixed 2 errors, and lowered required NodeJS version

---

package.json
src/arguments/jsonTextComponent.ts
src/datapack/BasePath.ts
src/flow/Flow.ts
src/index.ts

Changelog:
- Fixed asynchronous `_.while` statements not working
- Added defaults generics to `BasePathInstance` & `BasePathClass`
- Now exporting `BasePathInstance`
- Added the `extra` property on `JsonTextComponents`

Fixed a bunch of bugs

---

package.json
src/commands/CommandsRoot.ts
src/commands/implementations/Data.ts
src/commands/implementations/Execute.ts
src/commands/implementations/Experience.ts
src/commands/implementations/Teleport.ts
src/commandsOnly.ts
src/datapack/resourcesTree.ts
src/flow/Flow.ts
src/flow/conditions.ts

Changelog:
- `execute.ifScore/Block/Data...` are all replaced by `execute.if.score/block/data...`.
- `data.modify...fromEntity/Storage/Block` are all replaced by `data.modify...from.entity/storage/block`.
- Added all command aliases (`tp`, `w`, `tm`, `xp` and `tell`).
- Commands with aliases (`experience`, `teleport`...) will now compile to their smallest alias.
- Fixed `_.data` not being a correct argument for `_.if`.
- Fixed incorrect warnings about functions being overriden.

Changes in execute.if & data

---

package.json
src/arguments/jsonTextComponent.ts
src/arguments/resources/advancement.ts
src/arguments/resources/lootTables.ts
src/commands/CommandsRoot.ts
src/commands/decorators.ts
src/commands/implementations/Bossbar.ts
src/commands/implementations/Execute.ts
src/commands/implementations/Scoreboard.ts
src/commands/implementations/Team.ts
src/commands/implementations/Title.ts
src/datapack/Datapack.ts
src/datapack/saveDatapack.ts
src/index.ts
src/resources/Advancement.ts
src/resources/LootTable.ts
src/resources/Predicate.ts
src/resources/Recipe.ts
src/variables/JsonTextComponentClass.ts
src/variables/Objective.ts
src/variables/PlayerScore.ts
src/variables/Selector.ts
src/variables/abstractClasses.ts
src/variables/index.ts

Changelog:
- Fixed `execute.if.<something>` adding a 'if data' in the output.
- Renamed all internal types & classes mentionning `Json` to `JSON`.
- Removed `readonly` property on `JsonTextComponent`, and changed `extra` to be an array of `JsonTextComponents`.
- Selectors now support multiple negative gamemodes: `gamemode: ['!creative', '!survival']`

Fixed a bunch of bugs & renamed some types

---

src/commands/implementations/Scoreboard.ts

`createObjective` was separated into `Objective.create` and `Objective.get`; I changed the TSDoc to reflect this. The website docs should probably be changed too. I am definitely not salty about the fact that I spent 10 minutes trying to figure out why I couldn't import `createObjective`.

Update TSDoc to match changes to Objective abstraction

---

src/arguments/resources/lootTables.ts

I was building out a loot table and saw that 1) `ore_drops` was misspelled as `ore_rops` and 2) I had to create a `parameters` object for `ore_drops` even though it doesn't accept parameters. This fixes both of those with some basic type updates.

Fixed type and improved typing for formulas.

---

src/datapack/BasePath.ts

namespaces do not support dots in their names, despite the fact that minecraft can

---

src/datapack/resourcesTree.ts
src/resources/Tag.ts
src/variables/Data.ts

In some places, when compiling with `tsc`, an implicit any type error is thrown, the editor also complains about those errors:
This pull request fixes that by adding proper type definitions

Added type definitions to fix implicit types

---

src/datapack/filesystem.ts
src/datapack/saveDatapack.ts
src/resources/MCFunctionClass.ts
src/utils.ts
src/variables/NBTs.ts
src/variables/parsers.ts

In some modules without import, for example `util`, `import util from 'util'` is allowed but the imported module has `any` type. This may lead to situations like this: `util.inspect.custom` has `any` type, thus `NBTCustomObject` matches any type with `toString(): string`.
This pull request fixed that by using `import * as ... from ...` for modules without default import.

Fix default imports in modules without default import

---

src/variables/Score.ts

This pull request adds alternatives to verbose methods of Score. For example, `Score.greaterOrEqualThan` can be replaced by `Score['>=']`.

Add less verbose options to Score

---

src/commands/CommandsRoot.ts
src/resources/Tag.ts

- In JSON, tags are referenced by their namespaced name without # prefix.
- `clear` command accepts item tags

Fixed item tags having # when converted to JSON

---

src/variables/Coordinates.ts

Current behavior of `relative` and `local` function:
```typescript
relative()        // Expected at least 1 arguments, but got 0.
relative(0)       // '~'
relative(0, 0, 0) // ['~', '~', '~']
local()           // Expected at least 1 arguments, but got 0.
local(0)          // '^'
local(0, 0, 0)    // ['^', '^', '^']
```
New behavior:
```typescript
relative()         // ['~', '~', '~']
relative(0)        // '~'
relative(0, 0, 0)  // ['~', '~', '~']
local()            // ['^', '^', '^']
local(0)           // '^'
local(0, 0, 0)     // ['^', '^', '^']
```
With this PR, `relative()` and `local()` is the same as doing `relative(0, 0, 0)` and `local(0, 0, 0)`.
Tell me if you see anything to improve.
You can test this PR using `npm i aeryle/sandstone`

Make rel() and loc() return default values if no argument is passed

---

src/variables/JSONTextComponentClass.ts

The `JSONTextComponentClass` parser does not currently correctly parse root components with a `_toChatComponent` or `toJSON` functions, only those nested inside them.
This can cause problems as demonstrated in #102.

Parse root JSON component correctly

---

src/commands/implementations/worldborder.ts

It now accepts vec2 coordinate instead of vec3.
Incorrect:
Correct:

Fixed worldborder.center command

---

src/arguments/resources/datapack/structure.ts
src/commands/implementations/block/place.ts
src/core/resources/resourcepack/model.ts
src/index.ts

The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all the URLs to the new domain: minecraft.wiki

Update Minecraft Wiki links to new domain after fork

---

.github/workflows/test.yml
src/arguments/resources/datapack/tag.ts
src/commands/implementations/block/place.ts
src/commands/implementations/entity/execute.ts
src/core/resources/resource.ts
src/core/sandstoneCore.ts
src/pack/visitors/containerCommandsToMCFunction.ts
src/variables/parsers.ts
tests/text/flow/if.test.ts

Using a high number of recursive `If` was slowing down the compilation.
Profiling showed the bottleneck was `handleConflict`, a `O(N)` operation that happens everytime we add a new Node.
I switched the `resourceNodes` `Set` to a "custom" `Map` class, `ResourceNodesMap`. This automatically manages the Map keys by concatenating the packType and the path components.
* Generating 1500 nested `if` took `33.430s`
* Generating 100k sequential `if` took `17.02s`
* Generating 5000 nested `if` now takes `0.889s` (x37 🚀)
* Generating 100k sequential `if` now takes `2.254s` (x7.5 🚀 )
More generally, the new O(1) complexity means Sandstone will better scale on large projects.

Performance improvements
